# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ed21181b8928c24e8008f8b60afe78e75e80444ba4bf1630e3029ce457013135201569018f7378cc27d0a82f46d7274da9ae909489efd14d44992c40c93d2a

test:
  secret_key_base: de3cde7f9c4b2bcebc907fb26f2e963c8dda157206e064e0343d6e14783310d00e57a1e63aee38c7ce2d1192d8dd0a842d0134a088f871952a09b34bdffe7da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
